### PR TITLE
keep track of source number and url

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
@gudrutis , I would suggest the following
- in `def fetchSources ()` pass `pkg` to `download()` call instead of `pkg.options`
- in `download()` you can access `pkg.sourcesNumbers[source]` to get the source number for a url.
- use pkg.options to check if user has asked to override pkg.name:source via command line

**Comment by gudrutis** [comment]
@smuzaffar , I changed this fuction from 
https://github.com/gudrutis/pkgtools/blob/1c686e6e23a858630fbfe21250ab63760f7a5a43/cmsBuild#L600

to 

```python
def download(source, dest, pkg):
```

but I noticed that `download` fuction is called in  `getSpecRepository` as well.

https://github.com/gudrutis/pkgtools/blob/1c686e6e23a858630fbfe21250ab63760f7a5a43/cmsBuild#L3596

the `getSpecRepository` fuctions (link above) does not have pkg object, so my workaround is 
```python
download (url, destTmpDir, {"options": options})
```
Do you agree?

**Comment by smuzaffar** [comment]
@gudrutis , ah right. I guess then change the download function to 
`def download (source, dest, options, pkg=None): `
and only override the source if pkg is passed.

**Comment by gudrutis** [comment]
I had 2 ways how to read --source option to able to put multiple pkg:source from command line.
This:
```
./cmsBuild --source "package1=/tmp;package1:source2=/tmp;package2:source1=/tmp"  (other options)
```
Or this:
```bash
./cmsBuild --source package1=/tmp --source package1:source2=/tmp --source package2:source1=/tmp  (other options)
```
I went with the second option in this commit.
https://github.com/gudrutis/pkgtools/commit/88044da67afacb9e2659c98f42294fb060a849d6

But I think if I used 1st option, I could have used OptParse callback and make code it a bit more elegant.

**Comment by smuzaffar** [comment]
I prefer `./cmsBuild --source package1=/tmp --source package1:source2=/tmp`  which is easier for users to use. https://github.com/gudrutis/pkgtools/commit/88044da67afacb9e2659c98f42294fb060a849d6 seems resonable

**Comment by gudrutis** [comment]
I also reformated `cmsBuild` to PEP standard since my IDEA kept insisting (commit below). Now I noticed it put 4 spaces instead of 2. Do you object or I can keep it this way?
 
https://github.com/gudrutis/pkgtools/commit/df26e050bdbcdaca6b7ba84e42477ac486807262

**Comment by smuzaffar** [comment]
lookgs good, keep it as it is.

**Pull request merged**
